language: python
python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=settings

matrix:
  include:
    - python: "2.7"
      env: DJANGO_SETTINGS_MODULE=settings
    - python: "3.5"
      env: DJANGO_SETTINGS_MODULE=settings
  allow_failures:
    - python: "3.5"
      env: DJANGO_SETTINGS_MODULE=settings

addons:
  firefox: "46.0"

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"

install:
    - npm install
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "pip install coveralls==1.1"

script:
    - tox
    - ./node_modules/gulp/bin/gulp.js test
    - bash ./run_bokchoy_tests.sh

after_success: coveralls

branches:
    only:
      - master
      - cdodge/mcka-master
      - cdodge/notification-digest
